-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Grammatica.

module Grammatica.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Grammatica.Abs

-- | The top-level printing method.

-- Mostra "file:line:col" se filename non è vuoto, altrimenti "line:col"
showPos :: Grammatica.Abs.SourcePos -> ShowS
showPos (Grammatica.Abs.SourcePos l c f) =
  (if null f then id else showString f . showChar ':') . shows l . showChar ':' . shows c

-- Doc con il tag posizione, es. @[12:7] o file.go:12:7
posDoc :: Grammatica.Abs.SourcePos -> Doc
posDoc p = doc (showChar '@' . showChar '[' . showPos p . showChar ']')

-- Stampa trasparente del contenuto + suffisso posizione
instance Print a => Print (Grammatica.Abs.Positioned a) where
  prt i (Grammatica.Abs.Positioned p x) = concatD [prt i x, posDoc p]

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Grammatica.Abs.Ident where
  prt _ (Grammatica.Abs.Ident i) = doc $ showString i
instance Print Grammatica.Abs.Boolean where
  prt i = \case
    Grammatica.Abs.Boolean_true -> prPrec i 0 (concatD [doc (showString "true")])
    Grammatica.Abs.Boolean_false -> prPrec i 0 (concatD [doc (showString "false")])

instance Print Grammatica.Abs.RExpr where
  prt i = \case
    Grammatica.Abs.Or rexpr1 rexpr2 -> prPrec i 0 (concatD [prt 0 rexpr1, doc (showString "||"), prt 1 rexpr2])
    Grammatica.Abs.And rexpr1 rexpr2 -> prPrec i 1 (concatD [prt 1 rexpr1, doc (showString "&&"), prt 2 rexpr2])
    Grammatica.Abs.Not rexpr -> prPrec i 2 (concatD [doc (showString "!"), prt 3 rexpr])
    Grammatica.Abs.Eq rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString "=="), prt 4 rexpr2])
    Grammatica.Abs.Neq rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString "!="), prt 4 rexpr2])
    Grammatica.Abs.Lt rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString "<"), prt 4 rexpr2])
    Grammatica.Abs.LtE rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString "<="), prt 4 rexpr2])
    Grammatica.Abs.Gt rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString ">"), prt 4 rexpr2])
    Grammatica.Abs.GtE rexpr1 rexpr2 -> prPrec i 3 (concatD [prt 4 rexpr1, doc (showString ">="), prt 4 rexpr2])
    Grammatica.Abs.Add rexpr1 rexpr2 -> prPrec i 4 (concatD [prt 4 rexpr1, doc (showString "+"), prt 5 rexpr2])
    Grammatica.Abs.Sub rexpr1 rexpr2 -> prPrec i 4 (concatD [prt 4 rexpr1, doc (showString "-"), prt 5 rexpr2])
    Grammatica.Abs.Mul rexpr1 rexpr2 -> prPrec i 5 (concatD [prt 5 rexpr1, doc (showString "*"), prt 6 rexpr2])
    Grammatica.Abs.Div rexpr1 rexpr2 -> prPrec i 5 (concatD [prt 5 rexpr1, doc (showString "/"), prt 6 rexpr2])
    Grammatica.Abs.Mod rexpr1 rexpr2 -> prPrec i 5 (concatD [prt 5 rexpr1, doc (showString "%"), prt 6 rexpr2])
    Grammatica.Abs.Pow rexpr1 rexpr2 -> prPrec i 6 (concatD [prt 7 rexpr1, doc (showString "^"), prt 6 rexpr2])
    Grammatica.Abs.Neg rexpr -> prPrec i 7 (concatD [doc (showString "-"), prt 8 rexpr])
    Grammatica.Abs.Ref lexpr -> prPrec i 7 (concatD [doc (showString "&"), prt 0 lexpr])
    Grammatica.Abs.FCall funcall -> prPrec i 8 (concatD [prt 0 funcall])
    Grammatica.Abs.Int n -> prPrec i 9 (concatD [prt 0 n])
    Grammatica.Abs.Char c -> prPrec i 9 (concatD [prt 0 c])
    Grammatica.Abs.String str -> prPrec i 9 (concatD [prt 0 str])
    Grammatica.Abs.Float d -> prPrec i 9 (concatD [prt 0 d])
    Grammatica.Abs.Bool boolean -> prPrec i 9 (concatD [prt 0 boolean])
    Grammatica.Abs.GoArrayLit n basictype rexprs -> prPrec i 9 (concatD [doc (showString "["), prt 0 n, doc (showString "]"), prt 0 basictype, doc (showString "{"), prt 0 rexprs, doc (showString "}")])
    Grammatica.Abs.Lexpr lexpr -> prPrec i 12 (concatD [prt 0 lexpr])

instance Print Grammatica.Abs.FunCall where
  prt i = \case
    Grammatica.Abs.Call id_ rexprs -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 rexprs, doc (showString ")")])

instance Print [Grammatica.Abs.RExpr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Grammatica.Abs.LExpr where
  prt i = \case
    Grammatica.Abs.Deref rexpr -> prPrec i 0 (concatD [doc (showString "*"), prt 9 rexpr])
    Grammatica.Abs.PreInc lexpr -> prPrec i 1 (concatD [doc (showString "++"), prt 2 lexpr])
    Grammatica.Abs.PreDecr lexpr -> prPrec i 1 (concatD [doc (showString "--"), prt 2 lexpr])
    Grammatica.Abs.PostInc lexpr -> prPrec i 2 (concatD [prt 3 lexpr, doc (showString "++")])
    Grammatica.Abs.PostDecr lexpr -> prPrec i 2 (concatD [prt 3 lexpr, doc (showString "--")])
    Grammatica.Abs.BasLExpr blexpr -> prPrec i 2 (concatD [prt 0 blexpr])

instance Print Grammatica.Abs.BLExpr where
  prt i = \case
    Grammatica.Abs.ArrayEl id_ rexpr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 rexpr, doc (showString "]")])
    Grammatica.Abs.Id id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print Grammatica.Abs.Program where
  prt i = \case
    Grammatica.Abs.Prog decls -> prPrec i 0 (concatD [prt 0 decls])

instance Print [Grammatica.Abs.Decl] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Grammatica.Abs.Decl where
  prt i = \case
    Grammatica.Abs.Dfun id_ parameters compstmt -> prPrec i 0 (concatD [doc (showString "func"), prt 0 id_, doc (showString "("), prt 0 parameters, doc (showString ")"), prt 0 compstmt])
    Grammatica.Abs.DvarGo varspec -> prPrec i 0 (concatD [doc (showString "var"), prt 0 varspec, doc (showString ";")])

instance Print [Grammatica.Abs.Parameter] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Grammatica.Abs.Parameter where
  prt i = \case
    Grammatica.Abs.Param id_ typespec -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, prt 0 typespec])

instance Print Grammatica.Abs.VarSpec where
  prt i = \case
    Grammatica.Abs.VarSpecSingleInit id_ typespec rexpr -> prPrec i 0 (concatD [prt 0 id_, prt 0 typespec, doc (showString "="), prt 0 rexpr])
    Grammatica.Abs.VarSpecArrayInit id_ rexpr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 rexpr])
    Grammatica.Abs.VarSpecSingleNoInit id_ typespec -> prPrec i 0 (concatD [prt 0 id_, prt 0 typespec])

instance Print Grammatica.Abs.TypeSpec where
  prt i = \case
    Grammatica.Abs.BasTyp basictype -> prPrec i 0 (concatD [prt 0 basictype])
    Grammatica.Abs.CompType compoundtype -> prPrec i 0 (concatD [prt 0 compoundtype])

instance Print Grammatica.Abs.BasicType where
  prt i = \case
    Grammatica.Abs.BasicType_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    Grammatica.Abs.BasicType_char -> prPrec i 0 (concatD [doc (showString "char")])
    Grammatica.Abs.BasicType_float -> prPrec i 0 (concatD [doc (showString "float")])
    Grammatica.Abs.BasicType_int -> prPrec i 0 (concatD [doc (showString "int")])
    Grammatica.Abs.BasicType_string -> prPrec i 0 (concatD [doc (showString "string")])

instance Print Grammatica.Abs.CompoundType where
  prt i = \case
    Grammatica.Abs.ArrDef n typespec -> prPrec i 0 (concatD [doc (showString "["), prt 0 n, doc (showString "]"), prt 0 typespec])
    Grammatica.Abs.ArrUnDef typespec -> prPrec i 0 (concatD [doc (showString "["), doc (showString "]"), prt 0 typespec])
    Grammatica.Abs.Pointer typespec -> prPrec i 0 (concatD [doc (showString "*"), prt 0 typespec])

instance Print Grammatica.Abs.CompStmt where
  prt i = \case
    Grammatica.Abs.BlockDecl blockitems -> prPrec i 0 (concatD [doc (showString "{"), prt 0 blockitems, doc (showString "}")])

instance Print [Grammatica.Abs.BlockItem] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Grammatica.Abs.BlockItem where
  prt i = \case
    Grammatica.Abs.DeclItem decl -> prPrec i 0 (concatD [prt 0 decl])
    Grammatica.Abs.StmtItem stmt -> prPrec i 0 (concatD [prt 0 stmt])

instance Print [Grammatica.Abs.Stmt] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Grammatica.Abs.Stmt where
  prt i = \case
    Grammatica.Abs.Comp compstmt -> prPrec i 0 (concatD [prt 0 compstmt])
    Grammatica.Abs.ProcCall funcall -> prPrec i 0 (concatD [prt 0 funcall, doc (showString ";")])
    Grammatica.Abs.Jmp jumpstmt -> prPrec i 0 (concatD [prt 0 jumpstmt, doc (showString ";")])
    Grammatica.Abs.Iter iterstmt -> prPrec i 0 (concatD [prt 0 iterstmt])
    Grammatica.Abs.Sel selectionstmt -> prPrec i 0 (concatD [prt 0 selectionstmt])
    Grammatica.Abs.Assgn lexpr assignmentop rexpr -> prPrec i 0 (concatD [prt 0 lexpr, prt 0 assignmentop, prt 0 rexpr, doc (showString ";")])
    Grammatica.Abs.LExprStmt lexpr -> prPrec i 0 (concatD [prt 0 lexpr, doc (showString ";")])
    Grammatica.Abs.DeclStmt varspec -> prPrec i 0 (concatD [doc (showString "var"), prt 0 varspec, doc (showString ";")])
    Grammatica.Abs.StmtInc id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    Grammatica.Abs.StmtDec id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])

instance Print Grammatica.Abs.Assignment_op where
  prt i = \case
    Grammatica.Abs.Assign -> prPrec i 0 (concatD [doc (showString "=")])
    Grammatica.Abs.AssgnMul -> prPrec i 0 (concatD [doc (showString "*=")])
    Grammatica.Abs.AssgnAdd -> prPrec i 0 (concatD [doc (showString "+=")])
    Grammatica.Abs.AssgnDiv -> prPrec i 0 (concatD [doc (showString "/=")])
    Grammatica.Abs.AssgnSub -> prPrec i 0 (concatD [doc (showString "-=")])
    Grammatica.Abs.AssgnPow -> prPrec i 0 (concatD [doc (showString "^=")])
    Grammatica.Abs.AssgnAnd -> prPrec i 0 (concatD [doc (showString "&=")])
    Grammatica.Abs.AssgnOr -> prPrec i 0 (concatD [doc (showString "|=")])

instance Print Grammatica.Abs.JumpStmt where
  prt i = \case
    Grammatica.Abs.Break -> prPrec i 0 (concatD [doc (showString "break")])
    Grammatica.Abs.Continue -> prPrec i 0 (concatD [doc (showString "continue")])

instance Print Grammatica.Abs.SelectionStmt where
  prt i = \case
    Grammatica.Abs.IfNoElse rexpr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 rexpr, doc (showString ")"), prt 0 stmt])
    Grammatica.Abs.IfElse rexpr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 rexpr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])

instance Print Grammatica.Abs.IterStmt where
  prt i = \case
    Grammatica.Abs.While rexpr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 rexpr, doc (showString ")"), prt 0 stmt])
    Grammatica.Abs.DoWhile stmt rexpr -> prPrec i 0 (concatD [doc (showString "do"), prt 0 stmt, doc (showString "while"), doc (showString "("), prt 0 rexpr, doc (showString ")"), doc (showString ";")])
